[package]
name = "plonktest"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dusk-plonk = "0.8.1"
dusk-jubjub = "0.10.0"
rand_core = "0.6.3"
ansi_term = "0.12.1"